apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "orbital.fullname" . }}-services-config
data:
  services.conf: |-
    services {
      orbital-prometheus {
        url="http://{{ .Release.Name }}-kube-prometheus-st-prometheus.{{ .Release.Namespace }}.svc.cluster.local:9090"
      }
      orbital-server {
          rsocket="tcp://orbital.{{ .Release.Namespace }}.svc.cluster.local:7655"
          url="http://orbital.{{ .Release.Namespace }}.svc.cluster.local:9022"
      }
      stream-server {
          url="http://orbital-stream-server"
      }
    }
