apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "orbital.fullname" . }}-services-config
data:
  services.conf: |-
    services {
      {{- if or (not (empty .Values.prometheus.serviceUrl)) .Values.prometheus.enabled }}
      orbital-prometheus {
        {{- if not (empty .Values.prometheus.serviceUrl) }}
        url="{{- .Values.prometheus.serviceUrl }}"
        {{- else }}
        url="http://{{ .Release.Name }}-kube-prometheus-st-prometheus.{{ .Release.Namespace }}.svc.cluster.local:9090"
        {{- end }}
      }
      {{- end }}
    }
