{{- if not (empty $.Values.orbital.secretConfig) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "orbital.fullname" . }}-env
  labels: {{- include "orbital.metaLabels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $k, $v := $.Values.orbital.secretConfig }}
  {{ $k }}: {{ $v | toString }}
  {{- end }}
{{- end }}
