---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "orbital.fullname" . }}-stream-server
  labels: {{- include "streamServer.selectorLabels" . | nindent 4 }}
spec:
  type: {{ .Values.streamServer.service.type }}
  ports:
    - name: orbital-stream-server
      port: {{ .Values.streamServer.service.servicePort }}
      targetPort: {{ .Values.streamServer.service.containerPort }}
      appProtocol: http
      protocol: TCP
      {{- if (and (or (eq .Values.streamServer.service.type "LoadBalancer") (eq .Values.streamServer.service.type "NodePort")) (not (empty .Values.streamServer.service.nodePort))) }}
      nodePort: {{ .Values.streamServer.service.nodePort }}
      {{- end }}
    - name: stream-server-rsocket-tcp
      port: 7755
      targetPort: 7755
      appProtocol: tcp
      protocol: TCP
  selector: {{- include "streamServer.selectorLabels" . | nindent 4 }}
