{{- if .Values.serviceMonitor.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "orbital.fullname" . }}-service-monitor
  labels:
    release: {{ $.Release.Name | quote }}
spec:
  selector:
    matchLabels: {{- include "orbital.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: 'orbital-svc'
    path: /api/actuator/prometheus
    interval: 60s
    scheme: http
    scrapeTimeout: 30s
{{- end }}
